version: '2'
services:
    jhipsterangularjs-app:
        image: jhipsterangularjs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterangularjs-postgresql:5432/jHipsterAngularjs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterangularjs-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterangularjs-postgresql
